### ISSUE TITLE
Add some testings

### ISSUE THREAD

**Issue by MaaxIT** [Corentin-Julienne/webserv_42#2]
Testings and making sure everything works as required is an important part of our job in order to success the project.

Since we need to create a queue system for the incoming requests, it's important to make it efficient, and to know if it's the case, nothing's better than a stresser script.
It should be something easy-to-use and showing precise results.

We also need to create some fake websites to be sure that everything is working fine and that the multi-servers system is working even in a stressing situation.

**Comment by IsDoe** [comment]
Done
