### ISSUE TITLE
"Nginx" configuration parsing

### ISSUE THREAD

**Issue by MaaxIT** [Corentin-Julienne/webserv_42#6]
Every webserver will have a unique configuration file that we'll load and store when we're starting the service.

So, we'll need to find all configuration files, read them, parse them and store them (the best way to store them may be a Map since we're having the same Key=Value thing, but prove me wrong if you think I am).

Once it's stored, we must be able to access the data from the query execution part. Find the best way to keep the data (a structure?).

Of course, you'll need to check if all the mandatory configuration keyvalues are there. I guess you'll need to generate an error if there's not enough/too much data?

**Comment by Corentin-Julienne** [comment]
- parsing is know functional, should works, but I will search for additional bugs fore more safety before validating the project
